
USE l25arg8f6v01m4af;

CREATE TABLE burgers (
    id INTEGER AUTO_INCREMENT NOT NULL,
    name VARCHAR(100),
    devoured BOOLEAN DEFAULT false,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);  